export const GET_USERINFO_REQUEST = 'GET_USERINFO_REQUEST'
export const GET_USERINFO_SUCCESS = 'GET_USERINFO_SUCCESS'
export const GET_USERINFO_ERROR = 'GET_USERINFO_ERROR'

export const UPDATE_PROFILE = 'UPDATE_PROFILE'